### ISSUE TITLE
Pickaxe issue

### ISSUE THREAD

**Issue by KKrusteF** [MrMineO5/WickedPrison-Issues#6]
**Describe the bug**
Players can put their pickaxes in **/pv** or **chests**.
I have to idea how to replicate it the text Below is from other players.

**To Reproduce**
1. Go to survival mode
2. Open /pv or chest
3. Shift + Left-click your pickaxe and force close the inventory (press **ESC**)

**Expected behavior**
Players to not be able to put their pickaxes in pvs or chests.

**Screenshots**
none.

**Version (please complete the following information):**
 - Version all

**Additional context**
nope.

**Comment by MrMineO5** [comment]
With chests it does not work.

**Comment by MrMineO5** [comment]
It also does not work with PVs
